version: '3.9'

services:
  app:
    build: .
    container_name: status-app
    ports:
      - "8877:8877"
    environment:
      LOKI_HOST: "http://loki:3100/loki/api/v1/push"
    networks:
      - observability-net  # this is the external network

networks:
  observability-net:
    external: true