version: '3.9'

services:
  app:
    build: .
    container_name: status-app
    ports:
      - "8877:8877"
    environment:
      LOKI_HOST: "https://loki:3100/loki/api/v1/push"
    networks:
      - logging_default  # this is the external network

networks:
  logging_default:
    external: true